dist: focal
language: python
python:
  - "3.7"
services:
  - docker
env:
  - PY_VER=3.6.13
  - PY_VER=3.7.10
  - PY_VER=3.8.9
  - PY_VER=3.9.4

install: "" # so travis doesn't do pip install requirements.txt
script:
  - docker build -f py.Dockerfile --build-arg MUJOCO_KEY=$MUJOCO_KEY --build-arg PYTHON_VER=$PY_VER -t mod_gym-test .
  - docker run mod_gym-test

deploy:
    provider: pypi
    username: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
        tags: true
        condition: $PY_VER = 3.8.9
