from mod_gym.envs.toy_text.blackjack import BlackjackEnv
from mod_gym.envs.toy_text.roulette import RouletteEnv
from mod_gym.envs.toy_text.frozen_lake import FrozenLakeEnv
from mod_gym.envs.toy_text.nchain import NChainEnv
from mod_gym.envs.toy_text.hotter_colder import HotterColder
from mod_gym.envs.toy_text.guessing_game import GuessingGame
from mod_gym.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from mod_gym.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from mod_gym.envs.toy_text.cliffwalking import CliffWalkingEnv
from mod_gym.envs.toy_text.taxi import TaxiEnv
from mod_gym.envs.toy_text.guessing_game import GuessingGame
from mod_gym.envs.toy_text.hotter_colder import HotterColder
